
install:
    - curl -L0 https://github.com/gohugoio/hugo/releases/download/v0.68.3/hugo_extended_0.68.3_Linux-64bit.deb -o hugo.deb
    - sudo dpkg -i hugo.deb

script:
    - mkdir publish_scripts
    - git clone https://gist.github.com/c53a4394e556720b10a3fcd9e1a89841.git ./publish_scripts
    - hugo

deploy:
  - provider: script
    script: bash ./publish_scripts/publish_to_ghpages.sh
    skip_cleanup: true
    on:
      branch: master
